server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://root:Hf-gbAHaeFeE2ahcf6E6b45e3Dh6AHgd@monorail.proxy.rlwy.net:53866/railway
    username: root
    password: Hf-gbAHaeFeE2ahcf6E6b45e3Dh6AHgd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
security:
  jwt:
    secret: ghk45jgherogho834go3h4g
    issuer: Main
    ttlMillis: 604800000